{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discord-against-humanity.fullname" . }}
  labels:
    {{- include "discord-against-humanity.labels" . | nindent 4 }}
type: Opaque
data:
  DISCORD_TOKEN: {{ .Values.discordToken | b64enc | quote }}
{{- end }}
