services:
  bot:
    build: .
    environment:
      MONGO_HOST: "mongo"
      MONGO_PORT: "27017"
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
    networks:
      - internal
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    networks:
      - internal
    volumes:
      - mongo-data:/data/db

networks:
  internal:
    driver: bridge

volumes:
  mongo-data: {}
